config/routes.rb
Pinteresting::Application.routes.draw do
  resources :reservations
  resources :eateries
  resources :pins
  devise_for :users
  devise_for :installs
  root "pages#home"
  get "about" => "pages#about"
  get "show" => "pages#show"
  get "team" => "pages#team"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/eatery.rb
class Eatery < ApplicationRecord
validates :name, :address_street, :description, :address_state, :address_zip, :address_city, presence: {:message => "cannot be Blank"}
#validates :phone, length: { minimum: 10, maximum: 12}, numerically: true
validates :name, uniqueness: {case_sensitive: false}
validates :description, length: {maximum: 300}
validates :address_state, length:{maximum: 2}
  #has_many :reservations, dependent:, destroy:
  belongs_to :user
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/pin.rb
class Pin < ApplicationRecord
end

app/models/reservation.rb
class Reservation < ApplicationRecord
#validates :party_size, :date, :time, :presence {:message => "cannot be Blank"}

belongs_to :eatery
belongs_to :user
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/eateries_controller.rb
class EateriesController < ApplicationController
  before_action :set_eatery, only: [:show, :edit, :update, :destroy]

  # GET /eateries
  # GET /eateries.json
  def index
    @eateries = Eatery.all
  end

  # GET /eateries/1
  # GET /eateries/1.json
  def show
    @reservation = Reservation.new
  end

  # GET /eateries/new
  def new
    @eatery = Eatery.new
  end

  # GET /eateries/1/edit
  def edit
  end

  # POST /eateries
  # POST /eateries.json
  def create

    @eatery = Eatery.new(eatery_params)
    @eatery.user_id = current_user.id
    #@eatery = current_user.eateries.build(eatery_params)

    respond_to do |format|
      if @eatery.save
        format.html { redirect_to @eatery, notice: 'Eatery was successfully created.' }
        format.json { render :show, status: :created, location: @eatery }
      else
        format.html { render :new }
        format.json { render json: @eatery.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # one could add some validation here to check that the current user
    #matches the user associated witht the eatery
    respond_to do |format|
      if @eatery.update(eatery_params)
        format.html { redirect_to @eatery, notice: 'Eatery was successfully updated.' }
        format.json { render :show, status: :ok, location: @eatery }
      else
        format.html { render :edit }
        format.json { render json: @eatery.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    # one could add some validation here to check that the current user
    # matches the user associated witht the eatery
    @eatery.destroy
    respond_to do |format|
      format.html { redirect_to eateries_url, notice: 'Eatery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_eatery
      @eatery = Eatery.find(params[:id])
    end

  #  def current_user
  #    @eatery = current_user.eateries.find_by(:id params[:id])
  #    redirect_to eateries_path, notice: "Not authotized to edit this owner" if @eatery.nil?
  #  end

    def eatery_params
      params.fetch(:eatery, {})
      params.require(:eatery).permit(:name, :description, :address_zip, :address_state, :address_city, :address_street)

    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def team
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  def index
    @pins = Pin.all
  end

  def show
  end


  def new
    @pin = Pin.new
  end


  def edit
  end


  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :find_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @Reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:email, :date, :time, :name, :party_size, :comment, :user_id, :restrarant_id)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eateries_helper.rb
module EateriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/eateries/_form.html.erb
<%= form_for(@eatery) do |f| %>
  <% if @eatery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(eatery.errors.count, "error") %> prohibited this eatery from being saved:</h2>

      <ul>
      <% eatery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>

  <div class="field">

    <%= f.label :description %><br>
    <%= f.text_field :description, autofocus: true, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :address_street %><br>
    <%= f.text_field :address_street, autofocus: true, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :address_city %><br>
    <%= f.text_field :address_city, autofocus: true, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :address_zip %><br>
    <%= f.text_field :address_zip, autofocus: true, class: "form-control" %>
  <div class="field">
    <%= f.label :address_state %><br>
    <%= f.text_field :address_state, autofocus: true, class: "form-control" %>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, autofocus: true, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eateries/edit.html.erb
<h1>Editing Eatery</h1>

<%= render 'form', eatery: @eatery %>

<%= link_to 'Show', @eatery %> |
<%= link_to 'Back', eateries_path %>

app/views/eateries/index.html.erb
<p id="notice"><%= notice %></p>

<div class ="jumbotron center">



<h1>Eateries Listing</h1>

<table class="tables">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <div class ="center">
<tbody>
    <% @eateries.each do |eatery| %>

      <tr>
        <td><%= link_to eatery.name, eatery %><td><td id="notice"><%= notice %></td>
        <td><%= link_to 'show', eatery %></td>
        <td><%= link_to 'Edit', edit_eatery_path(eatery) %></td>
        <td><%= link_to 'Destroy', eatery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'New Reservation', new_reservation_path %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Eatery', new_eatery_path %>

<div>
  <dvv>

app/views/eateries/new.html.erb
<h1>New Eatery</h1>

<%= render 'form', eatery: @eatery %>

<%= link_to 'Back', eateries_path %>

app/views/eateries/show.html.erb
<h1><%= @eatery.name %></h1>
<h3><%= @eatery.phone %></h3>


<p id="notice"><%= notice %></p>
<%= render 'form' %>

<%= link_to 'Edit', edit_eatery_path(@eatery) %> |
<%= link_to 'Back', eateries_path %>

app/views/layouts/_header.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container"><!--/.container -->
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%=link_to"SpectrumR", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Home', root_path%></li>
      <li><%= link_to 'Team', team_path%></li>
      <li><%= link_to 'About', about_path%></li>
      <% if user_signed_in? %>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      </p>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinteresting</title>
    <%= csrf_meta_tags %>
    <meta name="viewprot" content="width=device-width, intital-scale=1.0">
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class:"alert alert-info") %>
    <%end%>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
  <p>Figuring out this rails stuff</p>

app/views/pages/home.html.erb
<div class ="jumbotron center">



  <h1>Welcome To The Breukelen</h1>
  <% if user_signed_in? %>

  <% else %>
  <p>
    <%= link_to "Login", user_session_path, class: "btn btn-primary btn-lg" %>
  <%= link_to "Signup", new_user_registration_path, class: "btn btn-primary btn-lg" %>
</p>
<%end%>

</div>

app/views/pages/team.html.erb
<h1>Our Team</h1>
  <p>Join Us today!!</p>

app/views/pins/_form.html.erb
<%= form_for(pin) do |f| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pins</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.description %></td>
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>

app/views/reservations/_form.html.erb
<%= form_for(reservation) do |f| %>
  <%= if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/_new.html.erb
  <% if @reservation.errors.any? %>
    <ul class="error_list">
      <% @reservation.errors.full_messages.each do |msg| %>
        <Li><%= msg %></li>
    <% end %>
<% end %>
    </ul>

<%= form_for(@reservation) do |f| %>
  <div class="field">
    <%= f.label :eatery %><br>
    <%= f.text_field :eatery %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :party_size %><br>
    <%= f.text_field :party_size %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time, ampm: true %>
  </div>
<div>
   <%= f.hidden_field :eatery_id, :value => @eatery %>
   <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<%end%>



<%= link_to 'Back', reservations_path %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>Make a Reservation</h1>

<%= render 'new' %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<% render 'new' %>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>